### PR TITLE
New Feature for m2e-ajdt: added possibility, to disable adding of adjust nature

### PR DESCRIPTION
**Pull request by barclay-reg**
Hi Andrew,

I'm requesting this to you, as I hope, that you've created the latest version (0.14) of this plugin.
Feel free, to give me more advices, if this is not the case

so long
Robert

### CODE REVIEW

**Comment by aeisenberg** [comment]
I'll take a look at the failing test. I won't have time for a few days, though.  Please remove the commit for travis-ci and adding the intellij files. You can add a *.iml line in the .gitignore, but they shouldn't be included in the repo.  Lastly, please squash this into a single commit.

**Comment by barclay-reg** [comment]
done so, hope that github will accept the rebase

**Comment by aeisenberg** [comment]
This commit still has the *.iml files and the travis file included. Please remove them and it will be ready to go in. Thanks.

**Comment by barclay-reg** [comment]
so, this should be the final commit

**Comment by aeisenberg** [comment]
Great. Code looks good. Just verifying the build is still working.

**Comment by barclay-reg** [comment]
any news about this merge?
when may I expect the new release to see in m2e discovery catalog?

**Comment by aeisenberg** [comment]
Had some trouble running the tests for your change. Turns out the fixes were due to some old code. Your change is now merged. I'll look into updating this for the discovery catalog. Thanks for your patch and apologies for the long turnaround time.

**Comment by barclay-reg** [comment]
may I ask you to send me a notice, when a new release is available.
if there are other code changes, maybe it's worth to have the current active repository here at github?

**Comment by aeisenberg** [comment]
Yes, I'll keep you posted.

**Comment by aeisenberg** [comment]
Hi Robert,

The new update site is available here:
http://dist.springsource.org/release/AJDT/configurator-v2/

It contains your fix and some unrelated clean-ups.  Martin Lippert has
taken over and done the CI work to get the build out the door.

**Pull request merged**
